// resources/js/lib/components/app-scaffold/TopBar.svelte
<script lang="ts">
    import { Bell, Menu } from '@lucide/svelte';

    let { sideBarToggleOpen } = $props<{ sideBarToggleOpen: boolean }>();
</script>

<div class="flex flex-col min-h-[76px] justify-between border-b border-neutral-200 items-center px-6 xl:flex-row">
    <div class="w-full h-full flex justify-between items-center">
        <button
            class="block xl:hidden p-2 border border-neutral-200 hover:bg-neutral-100"
            onclick={(e) => {
                e.stopPropagation();
                sideBarToggleOpen();
            }}
        >
            <Menu size={18} />
        </button>
        <div class="ml-auto flex items-center gap-4">
            <button class="p-2 border border-neutral-200 hover:bg-neutral-100">
                <Bell size={18} />
            </button>
        </div>
    </div>
</div>

// resources/js/components/scaffolds/TopBar.tsx
import { Badge, Button } from '@heroui/react';
import { Bell, Menu } from 'lucide-react';

const TopBar = ({ sideBarToggleOpen }: { sideBarToggleOpen: () => void }) => {
    return (
        <div className="sticky top-0 z-40 flex min-h-[76px] w-full flex-col items-center justify-between border-b border-neutral-200 bg-white px-6 xl:flex-row">
            <div className="flex h-full w-full items-center justify-between">
                <Button onPress={sideBarToggleOpen} size="md" variant="ghost" isIconOnly className="xl:hidden">
                    <Menu size={18} />
                </Button>
                <div className="ml-auto flex items-center gap-4">
                    <Badge color="primary" content={5} shape="circle" size="lg">
                        <Button size="md" variant="ghost" isIconOnly>
                            <Bell size={18} />
                        </Button>
                    </Badge>
                </div>
            </div>
        </div>
    );
};

export default TopBar;
