// resources/js/pages/auth/Login.svelte
<script lang="ts">
    import Layout from '@/modules/auth/layouts/Layout.svelte';
    import { route } from 'ziggy-js';
    import { useForm } from '@inertiajs/svelte';

    const form = useForm({
        email: null,
        password: null,
        remember: false,
    });

    function submit(e) {
        e.preventDefault();
        $form.post('/login');
    }
</script>

<Layout>
    <div class="flex w-full h-full">
        <div class="flex flex-col w-full h-full items-center p-10 gap-5 md:p-20">
            <div class="flex flex-col text-center gap-[12px] mb-[64px]">
                <h1 class="">Sign In</h1>
                <p class="max-w-xl text-center text-secondary-main body2">
                    Back in action. Let’s move your business forward.
                </p>
            </div>
            <form onsubmit={submit} class="flex flex-col w-full max-w-md gap-5">
                <div class="flex flex-col w-full">
                    <label for="email" class="w-full"> Email </label>
                    <input
                        type="text"
                        name="email"
                        id="email"
                        placeholder="example@company.com"
                        bind:value={$form.email}
                    />
                    {#if $form.errors.email}
                        <div class="input-error">
                            <p>{$form.errors.email}</p>
                        </div>
                    {/if}
                </div>
                <div class="flex flex-col w-full">
                    <label for="password" class="w-full"> Password </label>
                    <input
                        class="w-full"
                        type="password"
                        name="password"
                        id="password"
                        placeholder="Enter your password"
                        bind:value={$form.password}
                    />
                    {#if $form.errors.password}
                        <div class="input-error">
                            <p>{$form.errors.password}</p>
                        </div>
                    {/if}
                </div>
                <div class="flex w-full justify-between">
                    <div class="flex gap-2">
                        <input type="checkbox" name="remember" id="remember" bind:checked={$form.remember} />
                        <label for="remember"> Keep me logged in </label>
                    </div>
                    <a
                        href={route('password.request')}
                        class="text-sm text-primary-main hover:text-primary-dark underline self-end mb-1"
                    >
                        Forgot password?
                    </a>
                </div>
                <button
                    class="bg-primary-main text-white hover:bg-primary-dark self-start px-3 py-1.5 min-w-[120px]"
                    type="submit"
                    disabled={$form.processing}
                >
                    Sign In
                </button>
            </form>
            <div
                class="flex flex-col text-center w-full max-w-md mt-auto gap-2 md:gap-0 md:flex-row md:divide-x md:divide-secondary-lighter"
            >
                <p class="text-sm text-secondary-main hover:text-secondary-dark w-full">&#169; 2025 netbalance</p>
                <a href={route('policy')} class="text-sm text-secondary-main hover:text-secondary-dark w-full">
                    Privacy Policy
                </a>
                <a href={route('terms')} class="text-sm text-secondary-main hover:text-secondary-dark w-full">
                    Terms & Conditions
                </a>
            </div>
        </div>
        <div class="hero hidden flex flex-col w-full h-full items-center pt-20 gap-15 lg:flex">
            <div class="flex flex-col text-center px-20 gap-[12px]">
                <h2 class="text-primary-main">netbalance</h2>
                <p class="max-w-xl text-center text-secondary-main body2">
                    Streamline operations, optimize inventory, and gain powerful insights—all from one intuitive
                    platform that empowers your business to grow with clarity and control.
                </p>
            </div>
            <div class="relative w-full h-full px-20 overflow-hidden">
                <div class="hero-image w-full h-full absolute"></div>
            </div>
        </div>
    </div>
</Layout>

<style lang="css">
    .hero {
        background-color: rgb(245, 242, 250);
    }

    .hero-image {
        background-image: url('/images/dashboard-customer.svg');
    }
</style>

// resources/js/pages/auth/Login.tsx
import AuthLayout from '@/layouts/AuthLayout';
import { useForm } from '@inertiajs/react';
import { ReactNode } from 'react';

const LoginPage = () => {
    const { data, setData, post, processing, errors } = useForm({
        email: '',
        password: '',
        remember: false,
    });

    function submit(e: Event) {
        e.preventDefault();
        post('/login');
    }

    return (
        <>
            <div className="flex h-full w-full flex-col items-center gap-5 p-10 md:p-20">
                <div className="mb-[64px] flex flex-col gap-[12px] text-center">
                    <h1 className="">Sign In</h1>
                    <p className="text-secondary-main body2 max-w-xl text-center">
                        Back in action. Let’s move your business forward.
                    </p>
                </div>
                <form onSubmit={submit} className="flex w-full max-w-md flex-col gap-5">
                    <div className="flex w-full flex-col">
                        <label htmlFor="email" className="w-full">
                            Email
                        </label>
                        <input
                            type="text"
                            name="email"
                            id="email"
                            placeholder="example@company.com"
                            value={data.email}
                            onChange={(e) => setData('email', e.target.value)}
                        />
                        {errors.email && (
                            <div className="input-error">
                                <p>{errors.email}</p>
                            </div>
                        )}
                    </div>
                    <div className="flex w-full flex-col">
                        <label htmlFor="password" className="w-full">
                            Password
                        </label>
                        <input
                            className="w-full"
                            type="password"
                            name="password"
                            id="password"
                            placeholder="Enter your password"
                            value={data.password}
                            onChange={(e) => setData('password', e.target.value)}
                        />
                        {errors.password && (
                            <div className="input-error">
                                <p>{errors.password}</p>
                            </div>
                        )}
                    </div>
                    <div className="flex w-full justify-between">
                        <div className="flex gap-2">
                            <input
                                type="checkbox"
                                name="remember"
                                id="remember"
                                checked={data.remember}
                                onChange={(e) => setData('remember', e.target.checked)}
                            />
                            <label htmlFor="remember"> Keep me logged in </label>
                        </div>
                        <a
                            href={route('password.request')}
                            className="text-primary-main hover:text-primary-dark mb-1 self-end text-sm underline"
                        >
                            Forgot password?
                        </a>
                    </div>
                    <button
                        className="bg-primary-main hover:bg-primary-dark min-w-[120px] self-start px-3 py-1.5 text-white"
                        type="submit"
                        disabled={processing}
                    >
                        Sign In
                    </button>
                </form>
                <div className="md:divide-secondary-lighter mt-auto flex w-full max-w-md flex-col gap-2 text-center md:flex-row md:gap-0 md:divide-x">
                    <p className="text-secondary-main hover:text-secondary-dark w-full text-sm">
                        &#169; 2025 netbalance
                    </p>
                    <a href={route('policy')} className="text-secondary-main hover:text-secondary-dark w-full text-sm">
                        Privacy Policy
                    </a>
                    <a href={route('terms')} className="text-secondary-main hover:text-secondary-dark w-full text-sm">
                        Terms & Conditions
                    </a>
                </div>
            </div>
            <div className="hidden h-full w-full flex-col items-center gap-15 bg-[#f5f2fa] pt-20 lg:flex">
                <div className="flex flex-col gap-[12px] px-20 text-center">
                    <h2 className="text-primary-main">netbalance</h2>
                    <p className="text-secondary-main body2 max-w-xl text-center">
                        Streamline operations, optimize inventory, and gain powerful insights—all from one intuitive
                        plathtmlForm that empowers your business to grow with clarity and control.
                    </p>
                </div>
                <div className="relative h-full w-full overflow-hidden px-20">
                    <div className="absolute h-full w-full rounded-lg bg-[url(/images/dashboard-customer.svg)]"></div>
                </div>
            </div>
        </>
    );
};

LoginPage.layout = (page: ReactNode) => <AuthLayout children={page} />;

export default LoginPage;
